language: python
matrix:
    include:
        - python: 3.5
          dist: trusty
        - python: 3.6
          dist: trusty
          before_install:
            - python3 -m pip install -U pip setuptools setuptools-rust
        - python: 3.7
          dist: xenial
          before_install:
            - pip3 install setuptools-rust
        - python: 3.8
          dist: xenial
        - os: windows
          language: shell
          python: 3.7
          before_install:
            - choco install python3 --version=3.7.4
            - choco install openssl --version=1.1.1.900
            - pip install ntc_templates==1.4.1
            - pip install textfsm==0.4.1
          env:
            - PATH=/c/Python37:/c/Python37/Scripts:$PATH
            - TRAVIS_PYTHON_VERSION=3.7
            - CRYPTOGRAPHY_DONT_BUILD_RUST=1
            - INCLUDE='C:\OpenSSL-Win32\include;C:\OpenSSL-win64\include'
            - LIB='C:\OpenSSL-Win32\lib;C:\OpenSSL-win64\lib'
addons:
  apt:
    packages:
    - python-dev
    - libxml2-dev
    - libxslt1-dev

install:
  - "set"
  - "pip install -r development.txt"
  - "pip install -r requirements.txt"
  - "pip install ."
  - if [[ $TRAVIS_PYTHON_VERSION > 3.5 ]]; then pip install -U black; fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION > 3.5 ]]; then black --check --exclude=docs/* . ; fi
  - nosetests -v --with-coverage --cover-package=jnpr.junos --cover-inclusive -a unit

after_success:
  coveralls

notifications:
  email: false
